import uuid
from datetime import datetime,timezone
from sqlalchemy import DateTime,Integer,String,Text
from sqlalchemy.dialects.postgresql import JSONB,UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.database import Base
class AnalysisRecord(Base):
    __tablename__="analyses"
    id:Mapped[uuid.UUID]=mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )
    repository_url:Mapped[str]=mapped_column(
        Text,
        nullable=False
    )
    repository_name:Mapped[str]=mapped_column(
        String(255),
        nullable=False
    )
    base_ref:Mapped[str]=mapped_column(
        String(255),
        nullable=False,
        default="main"
    )
    target_ref:Mapped[str]=mapped_column(
        String(255),
        nullable=False,
        default="HEAD"
    )
    commit_sha:Mapped[str|None]=mapped_column(
        String(64),
        nullable=True
    )
    status:Mapped[str]=mapped_column(
        String(32),
        nullable=False,
        default="queued",
        index=True
    )
    progress:Mapped[int]=mapped_column(
        Integer,
        nullable=False,
        default=0
    )
    current_stage:Mapped[str]=mapped_column(
        String(64),
        nullable=False,
        default="queued"
    )
    overall_risk_score:Mapped[int|None]=mapped_column(
        Integer,
        nullable=True
    )
    overall_risk_level:Mapped[str|None]=mapped_column(
        String(32),
        nullable=True
    )
    result:Mapped[dict|None]=mapped_column(
        JSONB,
        nullable=True
    )
    error_message:Mapped[str|None]=mapped_column(
        Text,
        nullable=True
    )
    created_at:Mapped[datetime]=mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda:datetime.now(timezone.utc)
    )
    started_at:Mapped[datetime|None]=mapped_column(
        DateTime(timezone=True),
        nullable=True
    )
    completed_at:Mapped[datetime|None]=mapped_column(
        DateTime(timezone=True),
        nullable=True
    )